### ISSUE TITLE
crash when adding a sequencer

### ISSUE THREAD

**Issue by sjomae** [emuse/qmidiarp#16]
```
$ qmidiarp -v
 QMidiArp 0.7.0

arch linux


$ qmidiarp
Internal Transport stopped
jack process callback registered
/usr/include/c++/14.1.1/bits/stl_vector.h:1130: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = Sample; _Alloc = std::allocator<Sample>; reference = Sample&; size_type
= long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)

**Comment by sjomae** [comment]
When adding the LV2 sequencer plugin to Carla, Carla crashes. The arp and lfo seems to be working.

**Comment by emuse** [comment]
Hi, this looks like issue #4 that I was / am unable to reproduce. Are you using the ArchLinux package version? Can you try to pull from github repo and build qmidiarp yourself? 
after git pull you need to run autoreconf -i in the source tree before running ./configure --prefix=/usr

Thanks
Frank

**Comment by emuse** [comment]
I just committed a potential fix, but I cannot verify because I cannot reproduce the issue.

**Comment by sjomae** [comment]
standalone works now, Carla still crashes. Thanks.

```
# carla -v
Using Carla version 2.5.8
  Python version: 3.12.4
  Qt version:     5.15.14
  PyQt version:   5.15.11

**Comment by sjomae** [comment]
My bad, arch linux has a dedicated package for the plugin version, it works in Carla after I removed those.

**Comment by emuse** [comment]
QMidiarp Seq LV2 works in Carla 2.4.2 here (I cannot try a later version). So it does with qtractor, ardour 6 and jalv.qt5 / jalv.gtk on Ubuntu 22.04. I will still investigate what may be going wrong.

**Comment by emuse** [comment]
OK, our comments crossed....

Thanks for the feedback

**Comment by sjomae** [comment]
Thanks for your work on this small ugly but surprisingly useful tool. ;)
