### ISSUE TITLE
Build fails on Debian Buster

### ISSUE THREAD

**Issue by tcrass** [emuse/qmidiarp#6]
Hi,

after successfully configuring the git master checkout (current commit is 28cb06b), make fails eventually with

```
[...]
libtool: compile:  g++ -std=c++11 -Wall -Wextra -Wno-deprecated-copy -D_REENTRANT -DHAVE_CONFIG_H -I. -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/x86_64-linux-gnu/qt5 -fPIC -g -O2 -MT midiarp_lv2.lo -MD -MP -MF .deps/midiarp_lv2.Tpo -c midiarp_lv2.cpp  -fPIC -DPIC -o .libs/midiarp_lv2.o
In file included from midiarp_lv2.h:29,
                 from midiarp_lv2.cpp:27:
lv2_common.h:28:10: fatal error: lv2/ui/ui.h: No such file or directory
 #include "lv2/ui/ui.h"
          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:1400: midiarp_lv2.lo] Error 1
make[3]: Leaving directory '/home/tcrass/src/qmidiarp/src'
make[2]: *** [Makefile:2238: all-recursive] Error 1
make[2]: Leaving directory '/home/tcrass/src/qmidiarp/src'
make[1]: *** [Makefile:948: all] Error 2
make[1]: Leaving directory '/home/tcrass/src/qmidiarp/src'
make: *** [Makefile:675: all-recursive] Error 1
```

Cheers --

    Torsten

**Comment by emuse** [comment]
Hi Torsten,
which lv2 version are you building against?

Cheers
Frank

**Comment by tcrass** [comment]
Frank,

apt says: 1.14.0~dfsg1-2

I'm trying to build qmidiarp from the latest source because the pre-compiled version coming with Debian Buster (0.6.5-1) doesn't sync with qtractor (latest AppImage) as host. Which is a pity, since what I read about qmidiarp sounds **_so_** good...

Cheers --

    Torsten

**Comment by emuse** [comment]
OK, I have reverted the include paths to the earlier format, I think it should work now with lv2 1.14, too.

Best

**Comment by tcrass** [comment]
Now it does work indeed! Thanks a lot! :)

Syncing with qtractor does, however, still not work -- I'll open a separate ticket for this.

Cheers --

    Torsten

**Comment by emuse** [comment]
OK I'm closing this since building works for you.
